-- AlterEnum: add new individual S3 config values
ALTER TYPE "AppConfigName" ADD VALUE 'STORAGE_S3_ENDPOINT';
ALTER TYPE "AppConfigName" ADD VALUE 'STORAGE_S3_BUCKET';
ALTER TYPE "AppConfigName" ADD VALUE 'STORAGE_S3_ACCESS_KEY_ID';
ALTER TYPE "AppConfigName" ADD VALUE 'STORAGE_S3_SECRET_ACCESS_KEY';
